---
title: "Normalizing data for estimation analysis"
author: "Rohan Mate"
date: "December 5, 2016"
output: html_document
---

#Based on the historical data (ClassifyRisk_historical.csv) try to classify new prospective #customers (classifyrisk.csv) into the risk classes (bad loss, good risk). Use k-nearest #neighbor algorithm


```{r}
require(caret)
require(class)
require(e1071)
data1 = read.csv("classifyrisk.csv", header = T)
data2 = read.csv("ClassifyRisk_historical.csv", header = T)
```

# For normalization

```{r}
norm.income <- (data2$income - min(data2$income)) / (max(data2$income) - min(data2$income))
head(norm.income)
norm.data2 = sapply(data2[2:3], function(x){(x-min(x))/(max(x) - min(x))})
head(data2)
head(norm.data2)
norm.data2 = data.frame(norm.data2, norm.income, data2$risk)
head(norm.data2)
```

# For dividing data into train and test
```{r}
x = sample(2, nrow(norm.data2), replace = T, prob = (c(0.67, 0.33)))
norm.data2.train = norm.data2[x==1,]
norm.data2.test = norm.data2[x==2,]
```

# For estimation
```{r}
norm.data2.estimation = knn(norm.data2.train[1:3], norm.data2.test[1:3], norm.data2.train$data2.risk, k = 6)
```

# For testing
```{r}
table(data.frame(norm.data2.estimation, norm.data2.test$data2.risk))
confusionMatrix(table(data.frame(norm.data2.estimation, norm.data2.test$data2.risk)))
```

# For normalizing the present data before estimation
```{r}
norm.income.p <- (data1$income - min(data1$income)) / (max(data1$income) - min(data1$income))
norm.income.p

norm.data.p = sapply(data1[2:3], function(x){(x-min(x))/(max(x) - min(x))})
head(norm.data.p)

norm.data.p = data.frame(norm.data.p, norm.income.p, data1$risk)
head(norm.data.p)
```

# For current estimation
```{r}
final.estimation = knn(norm.data2.train[1:3], norm.data.p[1:3], norm.data2.train$data2.risk, k = 9)
final.estimation
```


